secret/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('secretapp.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

secretapp/urls.py
from django.urls import path
from .views import HomeView, EncryptView, VerifyView, DecryptView, SuccessView

app_name = "secretapp"
urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path("encrypt/", EncryptView.as_view(), name="encrypt"),
    path("verify/", VerifyView.as_view(), name="verify"),
    path('decrypt/', DecryptView.as_view(), name="decrypt"),
    path('decryption-successfull/', SuccessView.as_view(), name="success")
]

secretapp/models.py
from django.db import models


class EncryptionData(models.Model):
    unique_string = models.CharField(max_length=50, unique=True)
    participants = models.PositiveIntegerField()
    threshold = models.PositiveIntegerField()
    shares = models.TextField()
    orginal_image = models.ImageField(upload_to='original_images')

    def __str__(self):
        return self.unique_string

secretapp/views.py
from PIL import Image
from django.contrib import messages
from django.core.mail import EmailMultiAlternatives
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView, View
import os
from numpy import *
from .encryption import imageEncryption, imageDecryption, changeImageToMatrix
from .models import EncryptionData


class HomeView(TemplateView):
    template_name = 'index.html'


class EncryptView(View):
    participants = [
        {"value": 3, "key": "Three"},
        {"value": 4, "key": "Four"},
        {"value": 5, "key": "Five"},
        {"value": 6, "key": "Six"},
        {"value": 7, "key": "Seven"},
        {"value": 8, "key": "Eight"},
        {"value": 9, "key": "Nine"}
    ]

    def get(self, request):
        return render(request, 'encrypt.html', {"participants": self.participants})

    def post(self, request):
        emails = []
        unique_string = request.POST['unique_string']
        db_ustring = EncryptionData.objects.filter(unique_string=unique_string)
        if db_ustring:
            return render(request, 'encrypt.html', {'participants': self.participants, "error": 'error'})
        else:
            participants = int(request.POST['participants'])
            threshold = int(request.POST['threshold'])

            for i in range(participants):
                emails.append(request.POST['email' + str(i)])

            image = request.FILES['image']
            share_list = imageEncryption(participants, threshold, image)
            en_str = ""
            for i in range(len(list(share_list))):
                for j in range(len(list(share_list[i]))):
                    for k in range(len(list(share_list[i][j]))):
                        for l in range(len(list(share_list[i][j][k]))):
                            en_str += str(share_list[i][j][k][l])
            for i in range(participants):
                im = Image.fromarray(share_list[i])
                im.save("image" + str(i) + ".png")
                subject = "secret image"
                text_content = 'your secret string is ' + unique_string
                message = EmailMultiAlternatives(subject, text_content, 'sachin.proshore@gmail.com', [emails[i]])
                message.attach_file('image' + str(i) + ".png")
                message.send()
                if os.path.exists("image" + str(i) + ".png"):
                    os.remove("image" + str(i) + ".png")
            print(type(share_list))
            print(type(share_list[0]))
            EncryptionData.objects.create(unique_string=unique_string,
                                          participants=participants,
                                          threshold=threshold,
                                          shares=en_str,
                                          orginal_image=image)
            messages.success(request, "Image is encrypted sucessfully!")
            return redirect(reverse('secretapp:home'))


class VerifyView(View):
    def get(self, request):
        return render(request, 'verify.html')

    def post(self, request):
        unique_string = request.POST['unique_string']
        udb_string = EncryptionData.objects.filter(unique_string=unique_string)
        if udb_string is None:
            messages.error(request, "Unique string you have inputed did'nt matched in database!")
            return redirect(reverse('secretapp:verify'))
        else:
            request.session['unique_string'] = unique_string
            return redirect(reverse('secretapp:decrypt'))


class DecryptView(View):

    def get(self, request):
        unique_string = request.session['unique_string']
        if unique_string:
            decryption_data = EncryptionData.objects.get(unique_string=unique_string)
            shares_num = range(decryption_data.threshold)
            return render(request, 'decrypt.html', {'shares_num': shares_num})
        else:
            messages.error(request, "verify the unique string first")
            return render(request, 'verify.html')

    def post(self, request):
        unique_string = request.session['unique_string']
        if unique_string:
            match = True
            decryption_data = EncryptionData.objects.get(unique_string=unique_string)
            threshold = decryption_data.threshold
            shares = decryption_data.shares
            duplicate_check = ""
            for i in range(threshold):
                img = changeImageToMatrix(request.FILES["image" + str(i)])
                img_str = ""
                for b in range(len(list(img))):
                    for j in range(len(list(img[b]))):
                        for k in range(len(list(img[b][j]))):
                            img_str += str(img[b][j][k])

                if img_str in duplicate_check:
                    match = False
                if img_str not in shares:
                    match = False
                if match == False:
                    messages.success(request, "You haven't meet minimum criteria to decryption!")
                    return redirect(reverse('secretapp:decrypt'))
                duplicate_check += img_str
            return redirect(reverse('secretapp:success'))
        else:
            messages.error(request, "Unique string did not matched!")
            return redirect(reverse('secretapp:verify'))


class SuccessView(View):
    def get(self, request):
        unique_string = request.session['unique_string']
        if unique_string:
            decryption_data = EncryptionData.objects.get(unique_string=unique_string)
            return render(request, 'success.html', {'image': decryption_data.orginal_image.url})
        else:
            messages.error(request, "Something went wrong")
            return redirect(reverse('secretapp:home'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-md bg-danger navbar-dark mb-5">
        <a class="navbar-brand" href="{% url 'secretapp:home'%}">Visual Secret Sharing</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav ml-auto mr-4">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'secretapp:home' %}">Home </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">FAQ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">User Manual</a>
                </li>
            </ul>

        </div>
    </nav>

     <div id="content" class="container">
        {% include 'messages.html' %}
        {% block message%}  {% endblock %}
     </div>

    {% block content %}

    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
     <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script>
</body>

</html>

templates/decrypt.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
vss decrypt
{% endblock %}

{% block content %}
<div class="card col-md-8 mx-auto shadow-lg p-3 mb-5 bg-white rounded " id="card">
    <h3 class="mt-4 text-center">Please fill the decryption details</h3>
    <form action="#" method="post" class="mt-4 px-3" enctype="multipart/form-data" id="form">
        {% csrf_token %}
        {% for i in shares_num %}
            <div class="form-group">
                <label>Share{{ i }}</label>
                <input type="file" name="image{{i}}" accept="image/*" required><br/>
            </div>
        {% endfor %}
    <input type="submit" value="Decrypt"  class="btn btn-danger" id="decrypt">
    </form>
</div>

    <div class="text-center mt-4" id="load">
        <img src="{% static 'loading.gif' %}" alt="" style="width:320px">
        <h5> Loading ...</h5>
        <p>Please wait while processing</p>
    </div>

    <script>
        var x = document.querySelector('#load');
        x.style.display = 'none';
        var y = document.querySelector('#form');
        y.addEventListener("submit", function(){
            var z = document.querySelector("#card");
            z.style.display = "none";
            x.style.display ="block";
        });
    </script>
{% endblock %}

templates/encrypt.html
{% extends 'base.html' %}
{% load static %}
{% block title %}

{% endblock %}

{% block content %}
<script>
    function setThreshold() {
        let threshold = [
            { "value": 2, "key": 'Two' },
            { "value": 3, "key": "Three" },
            { "value": 4, "key": "Four" },
            { "value": 5, "key": "Five" },
            { "value": 6, "key": "Six" },
            { "value": 7, "key": "Seven" },
            { "value": 8, "key": "Eight" },
            { "value": 9, "key": "Nine" }
        ];

        let total_shares = document.getElementById("participants").value;
        let thresholdid = document.getElementById("threshold");
        html = "";
        for (let i = 0; i < total_shares - 1; i++) {
            html += `<option value="${threshold[i].value}">${threshold[i].key}</option>`;
        }
        thresholdid.innerHTML = html;
        let emails = document.getElementById("emails");
        mails = `<div class="form-group">
                <label>Email of participant one</label>
                <input type="email" class="form-control" name="email0" required>
            </div>`;
        for (let i = 1; i < total_shares; i++) {
            mails += `<div class="form-group">
                        <label>Email of participant ${threshold[i-1].key}</label>
                        <input type="email" class="form-control" name="email${i}" required>
                    </div>`;
        }
        emails.innerHTML = mails;
    }

</script>
<div class="card col-md-8 mx-auto shadow-lg p-3 mb-5 bg-white rounded " id="card">
    <h3 class="mt-4 text-center">Please fill the encryption details</h3>
    <form action="/encrypt/" method="post" class="mt-4 px-3" enctype="multipart/form-data" id="form">
        {% csrf_token %}
        <div class="form-group">
            <label>Participants</label>
            <select class="form-control" name="participants" id="participants" onChange="setThreshold()">
                {% for participant in participants %}
                <option value="{{participant.value}}">{{participant.key}}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-group">
            <label>
                Threshold
            </label>
            <select class="form-control" name="threshold" id="threshold">
                <option value="2">Two</option>
            </select>
        </div>
        <div id="emails">
            <div class="form-group">
                <label>Email of participant one</label>
                <input type="email" class="form-control" name="email0" required>
            </div>
            <div class="form-group">
                <label>Email of participant two</label>
                <input type="email" class="form-control" name="email1" required>
            </div>
            <div class="form-group">
                <label>Email of participant three</label>
                <input type="email" class="form-control" name="email2" required>
            </div>
        </div>

        <div class="form-group">
            <label>Unique String</label><br>
            <input type="text" name="unique_string" required>
            {% if error %}
                <p style="color:#ff0000;">String already exists, please choose another!</p>
            {% endif %}
        </div>

        <div class="form-group">
            <label>Image to encrypt</label><br>
            <input type="file" name="image" accept="image/*" required>
        </div>

        <input type="submit" class="btn btn-danger mb-4" value="encrypt" id="encrypt"/>
    </form>
</div>

<div class="text-center mt-4" id="load">
    <img src="{% static 'loading.gif' %}" alt="" style="width:320px">
    <h5> Loading ...</h5>
    <p>Please wait while processing</p>
</div>
    <script>
        var x = document.querySelector('#load');
        x.style.display = 'none';
        var y = document.querySelector('#form');
        y.addEventListener("submit", function(){
            var z = document.querySelector("#card");
            z.style.display = "none";
            x.style.display ="block";
        });
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Visual secret sharing
{% endblock %}

{% block content %}
<div class="container main">
    <div class="jumbotron mt-5">
        <h1 class="display-4">Be Seured & Safe</h1>
        <p class="lead">Keep the group secrets even more secret with use of visual secrat sharing.</p>
        <hr class="my-4">
        <p>Let's try and get started</p>
        <a class="btn btn-success btn-lg mr-4"  href="{% url 'secretapp:encrypt' %}"  role="button">Encrypt</a>
        <a class="btn btn-info btn-lg"  href="{% url 'secretapp:verify' %}" role="button">Decrypt</a>
    </div>
</div>
{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="bg-light m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/success.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
verify
{% endblock %}

{% block content %}
<div class="pythoncol-md-8 mx-auto shadow-lg p-3 mb-5 bg-white rounded ">
    <h3 class="mt-4 text-center">Decryption successfull</h3>
    <img src="{{ image }}" alt="">
    {{ threshold }}
</div>
<div class="col-md-8 mx-auto ">
    <a href="{% url 'secretapp:home' %}" class="btn btn-danger btn-block mt-4 px-4">Back</a>
</div>
{% endblock %}

templates/verify.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
verify
{% endblock %}

{% block content %}
<div class="card col-md-8 mx-auto shadow-lg p-3 mb-5 bg-white rounded ">
    <h3 class="mt-4 text-center">Please enter the Unique String you get while encryption</h3>
    <form action="#" method="post" class="mt-4 px-3">
        <div class="form-group">
            {% csrf_token %}
            <label>Unique String</label>
            <input type="text" name="unique_string" class="form-control" required>
        </div>
        <input type="submit" class="btn btn-danger">
    </form>
</div>
<div class="col-md-8 mx-auto ">
    <a href="{% url 'secretapp:home' %}" class="btn btn-danger btn-block mt-4 px-4">Back</a>
</div>
{% endblock %}